version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./web-ui
      dockerfile: Dockerfile
    volumes:
      - ./web-ui:/app
      # - /app/node_modules
    environment:
      - REACT_APP_API_URL=/api
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - ./server/storage:/app/storage
    environment:
      - MONGO_SERVER_URL=mongodb:27017
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_DB_NAME=serverdb
      - DATA_STORAGE_PATH=/app/storage
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

volumes:
  mongodb_data:
